import './globals.css&apos;;
import type { Metadata } from &apos;next&apos;;
import { Inter } from &apos;next/font/google&apos;;

const inter = Inter({ subsets: [&apos;latin&apos;] });

export const metadata: Metadata = {
  title: &apos;Create Next App&apos;,
  description: &apos;Generated by create next app&apos;,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
